# Generated by Django 4.1.2 on 2022-12-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_mobile',
            name='recived_otp',
            field=models.IntegerField(null=True),
        ),
    ]
