# Generated by Django 4.1.2 on 2022-12-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0004_alter_user_mobile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_mobile',
            name='otp_exp_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='user_mobile',
            name='otp_send_time',
            field=models.TimeField(null=True),
        ),
    ]
